const INITIAL_INVESTMENT_AMOUNT_USD = 10000;
const SESSION_TIMEOUT_MILLI = 600000; // 10 minutes in milliseconds
const EXCHANGE_UPDATE_INTERVAL_MILLI = 900000; // 15 minutes
module.exports = { INITIAL_INVESTMENT_AMOUNT_USD, SESSION_TIMEOUT_MILLI, EXCHANGE_UPDATE_INTERVAL_MILLI };
