-- Set database to the correct one
USE forexDB;

-- Insert data into the CURRENCYS table
insert into
    currencys (uuid, country, name, code, symbolUnicodeHex)
values
(uuid(),'Albania','Lek','ALL','4c,65,6b'),
(uuid(),'Afghanistan','Afghani','AFN','60b'),
(uuid(),'Argentina','Peso','ARS','24'),
(uuid(),'Aruba','Guilder','AWG','192'),
(uuid(),'Australia','Dollar','AUD','24'),
(uuid(),'Azerbaijan','Manat','AZN','20bc'),
(uuid(),'Bahamas','Dollar','BSD','24'),
(uuid(),'Barbados','Dollar','BBD','24'),
(uuid(),'Belarus','Ruble','BYN','42,72'),
(uuid(),'Belize','Dollar','BZD','42,5a,24'),
(uuid(),'Bermuda','Dollar','BMD','24'),
(uuid(),'Bolivia','Bolíviano','BOB','24,62'),
(uuid(),'Botswana','Pula','BWP','50'),
(uuid(),'Bulgaria','Lev','BGN','43b,432'),
(uuid(),'Brazil','Real','BRL','52,24'),
(uuid(),'Brunei Darussalam','Dollar','BND','24'),
(uuid(),'Cambodia','Riel','KHR','17db'),
(uuid(),'Canada','Dollar','CAD','24'),
(uuid(),'Cayman Islands','Dollar','KYD','24'),
(uuid(),'Chile','Peso','CLP','24'),
(uuid(),'China','Yuan Renminbi','CNY','a5'),
(uuid(),'Colombia','Peso','COP','24'),
(uuid(),'Costa Rica','Colon','CRC','20a1'),
(uuid(),'Croatia','Kuna','HRK','6b,6e'),
(uuid(),'Cuba','Peso','CUP','20b1'),
(uuid(),'Czech Republic','Koruna','CZK','4b,10d'),
(uuid(),'Denmark','Krone','DKK','6b,72'),
(uuid(),'Dominican Republic','Peso','DOP','52,44,24'),
(uuid(),'East Caribbean','Dollar','XCD','24'),
(uuid(),'Egypt','Pound','EGP','a3'),
(uuid(),'El Salvador','Colon','SVC','24'),
(uuid(),'European Union','Euro','EUR','20ac'),
(uuid(),'Falkland Islands','Pound','FKP','a3'),
(uuid(),'Fiji','Dollar','FJD','24'),
(uuid(),'Ghana','Cedi','GHS','a2'),
(uuid(),'Gibraltar','Pound','GIP','a3'),
(uuid(),'Guatemala','Quetzal','GTQ','51'),
(uuid(),'Guernsey','Pound','GGP','a3'),
(uuid(),'Guyana','Dollar','GYD','24'),
(uuid(),'Honduras','Lempira','HNL','4c'),
(uuid(),'Hong Kong','Dollar','HKD','24'),
(uuid(),'Hungary','Forint','HUF','46,74'),
(uuid(),'Iceland','Krona','ISK','6b,72'),
(uuid(),'India','Rupee','INR','8377'),
(uuid(),'Indonesia','Rupiah','IDR','52,70'),
(uuid(),'Iran','Rial','IRR','fdfc'),
(uuid(),'Isle of Man','Pound','IMP','a3'),
(uuid(),'Israel','Shekel','ILS','20aa'),
(uuid(),'Jamaica','Dollar','JMD','4a,24'),
(uuid(),'Japan','Yen','JPY','a5'),
(uuid(),'Jersey','Pound','JEP','a3'),
(uuid(),'Kazakhstan','Tenge','KZT','43b,432'),
(uuid(),'Korea (North)','Won','KPW','20a9'),
(uuid(),'Korea (South)','Won','KRW','20a9'),
(uuid(),'Kyrgyzstan','Som','KGS','43b,432'),
(uuid(),'Laos','Kip','LAK','20ad'),
(uuid(),'Lebanon','Pound','LBP','a3'),
(uuid(),'Liberia','Dollar','LRD','24'),
(uuid(),'Macedonia','Denar','MKD','434,435,43d'),
(uuid(),'Malaysia','Ringgit','MYR','4d'),
(uuid(),'Mauritius','Rupee','MUR','20a8'),
(uuid(),'Mexico','Peso','MXN','24'),
(uuid(),'Mongolia','Tughrik','MNT','20ae'),
(uuid(),'Mozambique','Metical','MZN','4d,54'),
(uuid(),'Namibia','Dollar','NAD','24'),
(uuid(),'Nepal','Rupee','NPR','20a8'),
(uuid(),'Netherlands Antilles',' Guilder','ANG','192'),
(uuid(),'New Zealand','Dollar','NZD','24'),
(uuid(),'Nicaragua','Cordoba','NIO','43,24'),
(uuid(),'Nigeria','Naira','NGN','20a6'),
(uuid(),'Norway','Krone','NOK','6b,72'),
(uuid(),'Oman','Rial','OMR','fdfc'),
(uuid(),'Pakistan','Rupee','PKR','20a8'),
(uuid(),'Panama','Balboa','PAB','42,2f,2e'),
(uuid(),'Paraguay','Guarani','PYG','47,73'),
(uuid(),'Peru','Sol','PEN','53,2f,2e'),
(uuid(),'Philippines','Peso','PHP','20b1'),
(uuid(),'Poland','Zloty','PLN','7a,142'),
(uuid(),'Qatar','Riyal','QAR','fdfc'),
(uuid(),'Romania','Leu','RON','6c,65,69'),
(uuid(),'Russia','Ruble','RUB','20bd'),
(uuid(),'Saint Helena','Pound','SHP','a3'),
(uuid(),'Saudi Arabia','Riyal','SAR','fdfc'),
(uuid(),'Serbia','Dinar','RSD','414,438,43d,2e'),  
(uuid(),'Seychelles','Rupee','SCR','20a8'),
(uuid(),'Singapore','Dollar','SGD','24'),
(uuid(),'Solomon Islands','Dollar','SBD','24'),
(uuid(),'Somalia','Shilling','SOS','53'),
(uuid(),'South Africa','Rand','ZAR','52'),
(uuid(),'Sri Lanka','Rupee','LKR','20a8'),
(uuid(),'Sweden','Krona','SEK','6b,72'),
(uuid(),'Switzerland','Franc','CHF','43,48,46'),
(uuid(),'Suriname','Dollar','SRD','24'),
(uuid(),'Syria','Pound','SYP','a3'),
(uuid(),'Taiwan','New Dollar','TWD','4e,54,24'),
(uuid(),'Thailand','Baht','THB','e3f'),
(uuid(),'Trinidad and Tobago','Dollar','TTD','54,54,24'),
(uuid(),'Turkey','Lira','TRY','8378'),
(uuid(),'Tuvalu','Dollar','TVD','24'),
(uuid(),'Ukraine','Hryvnia','UAH','20b4'),
(uuid(),'United Kingdom','Pound','GBP','a3'),
(uuid(),'United States','Dollar','USD','24'),
(uuid(),'Uruguay','Peso','UYU','24,55'),
(uuid(),'Uzbekistan','Som','UZS','43b,432'),
(uuid(),'Venezuela','Bolívar','VEF','42,73'),
(uuid(),'Viet Nam','Dong','VND','20ab'),
(uuid(),'Yemen','Rial','YER','fdfc'),
(uuid(),'Zimbabwe','Dollar','ZWD','5a,24');

